import { compileFromFile } from 'json-schema-to-typescript';
import { readFile, writeFile } from 'node:fs/promises';

const output = await compileFromFile('schemas/dataset.schema.json', { bannerComment: '/* Generated by npm run contracts. Do not edit. */' });
const target = 'schemas/dataset.d.ts';
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Contract types drift: run npm run contracts');
} else {
  await writeFile(target, output);
}
